/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModeratorId } from './moderatorId';

/**
 * Each queue has a series of work that needs to be done.  As a moderator check out the next X items.  This will mean they will have a lock on those items so others can only READ them but cannot check them out at the same time.  This allows many moderators to work through the queue at the same time.  If you are submitting a new item leave this blank 
 */
export interface Checkout { 
    moderatorId?: ModeratorId;
    /**
     * Unixtimestamp (milliseconds since Epoch) of when it will expire.  After this date it is free to be checked out by others.
     */
    expires?: number;
}