/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModeratorId } from './moderatorId';
import { Topics } from './topics';

/**
 * A Moderator Decision made to an item
 */
export interface Decision { 
    moderatorId?: ModeratorId;
    /**
     * OVERWRITTEN The time when this decision was recorded unixtime (in milliseconds since Epoch)  Note that when you add a new item this field is overwritten with the current itme 
     */
    timestamp?: number;
    /**
     * How many seconds did they spent working on this item?  This should be the total items reviewed on this page divided by seconds spent.  You can pause the counter if they were inactive such as when they went for a coffee.  This will role into the moderators stats.   Client Side to allow for pausing but it reduces the authority of the stats for HR purposes as the moderator could taint it.
     */
    seconds?: number;
    /**
     * What tags (action) did they add to the item
     */
    tags?: Array<string>;
    /**
     * Remove tags that others have set.
     */
    tagsRemoved?: Array<string>;
    correctTopics?: Topics;
    reviewedTopics?: Topics;
}