/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The default behaviour is to just add the items which is also the fastest.  If they are new then they are queued.  If they are already in the system and dealt with close them.
 */
export interface DeduplicationStrategy { 
    /**
     * For de-duplication list the fields in order
     */
    fields?: Array<string>;
    /**
     * If the item is a duplicate and it is already closed then only reopen it after so many seconds since it was closed.  The default is 0 which means do not reopen.  For reported content we recommend 24 hours which is 86400 seconds.
     */
    reopenAfterXSeconds?: number;
    /**
     * If an item is repeated should it increase in priority?  This would make it no longer a FIFO (First in first out) out like queue where items go out in the order they went in.  A practical use case is for reported content by userId.  You would set the deduplication on the field reportedUserId and then tell it to increase the priority.  The users that are reported more often will be at the front of the workload allowing you to deal with your most serious offenders first.
     */
    prioritize?: boolean;
}