/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LanguageCode } from './languageCode';
import { Prediction } from './prediction';

/**
 * In order to understand text we need to know what language it is for. A request can be * for enable language detection.  Otherwise if the servers are divided into english, french, etc then use the language for the server.  If you don't know use the language the user has chosen for their UI
 */
export interface Language { 
    language: LanguageCode;
    /**
     * 2 char iso_code that was the originally sent in language. * for use language detection
     */
    languageRequested?: string;
    /**
     * If language detection was called what languages did it predict.  The key is the 2 char ISO language code and the value is the prediction.
     */
    detected?: Array<Prediction>;
}