/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueueLabels } from './queueLabels';
import { QueueTag } from './queueTag';
import { QueueTagsLabelGroups } from './queueTagsLabelGroups';

/**
 * these are the tags that this item can be labelled as and how they interact with each other
 */
export interface QueueTags { 
    /**
     * What kind of content can this be
     */
    contentType?: Array<QueueTag>;
    /**
     * Definition for which tags can be applied for labelling the queue items
     */
    labelGroups?: Array<QueueTagsLabelGroups>;
    labels?: QueueLabels;
}