/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModeratorId } from './moderatorId';

/**
 * If the item has been redacted we store some data here
 */
export interface QueueItemRedacted { 
    /**
     * This item has been manually redacted so can be kept for long term storage.
     */
    redactedText?: boolean;
    /**
     * This item has been manually redacted so can be kept for long term storage.
     */
    redactedUsername?: boolean;
    moderatorId?: ModeratorId;
    /**
     * Unixtimestamp (milliseconds since Epoch) when we should go through this item and redact and pseudonymize all the data for long term storage.  Set to 0 to keep the original.  If it has potential of grooming or a criminal activity you generally don't want to lose the record.  If it is under GDPR or CCPA right to be forgotten and you are not calling our api for right to be forgetten you likely want to set it to < 30 days so it automatically is pseudonymized prior to a typical acceptable wait period to do thier request.
     */
    pseudonymizedDate?: number;
}