/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A single tag that can be chosen
 */
export interface QueueTag { 
    /**
     * The label to show on the screen
     */
    name?: string;
    /**
     * The help or alternate text to show to explain what this is for
     */
    description?: string;
    /**
     * The tag code to store in the system
     */
    value?: string;
}