/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Human labels that can be added to this item
 */
export interface QueueLabels { 
    /**
     * What kind of tag is this  enum - A list of values.  Can only be one. Works like a radio button. tag - A single tag tags - A list of tags that you can choose 
     */
    type?: QueueLabels.TypeEnum;
    /**
     * The label to show on the screen
     */
    name?: string;
    /**
     * The help or alternate text to show to explain what this is for
     */
    description?: string;
    /**
     * Set this item to true when the moderator takes another actions
     */
    hooks?: Array<string>;
    /**
     * The tag code to store in the system
     */
    value?: string;
    /**
     * If the item is nested you can add more items here
     */
    values?: Array<QueueLabels>;
}
export namespace QueueLabels {
    export type TypeEnum = 'enum' | 'tag' | 'tags';
    export const TypeEnum = {
        Enum: 'enum' as TypeEnum,
        Tag: 'tag' as TypeEnum,
        Tags: 'tags' as TypeEnum
    };
}