/**
 * Inbox API
 * Manage work for human moderators by adding, checking out and completing work items. Store User Generated Content to the database.  This will store it twice, once in short-term storage in it's exact form amd again in long term storage in it's redacted and pseudonymized form 
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeduplicationStrategy } from './deduplicationStrategy';
import { Hooks } from './hooks';
import { Param } from './param';
import { QueueTags } from './queueTags';

export interface Queue { 
    /**
     * The screen visible name
     */
    name?: string;
    /**
     * List of filter sections available
     */
    filters?: Array<string>;
    /**
     * unique identifier for internal use
     */
    queueId?: string;
    /**
     * These are the fields required for this queue.  In OpenAPI format.
     */
    schema?: any;
    deduplicationStrategy?: DeduplicationStrategy;
    /**
     * You can customize some queues with UI elements and settings.  Each queue lists what can be customized here
     */
    params?: Array<Param>;
    tags?: QueueTags;
    hooks?: Hooks;
}